### ISSUE TITLE
from the zoom chat at FORCE2021 day 2

### ISSUE THREAD

**Issue by johav** [mrchristian/UNESCO-Recommendation-on-Open-Science#1]
I can only help you mirror your own comments :)

- embed metadata
- TOC
- PDF bookmarks
- update to CC BY 4.0
- …

**Comment by mrchristian** [comment]
tick done, also doc lang was set as French - https://github.com/mrchristian/UNESCO-Recommendation-on-Open-Science/blob/main/pdf%2Bbookmarks%2Bmeta/379949eng-bookmarks-metadata.pdf

FYI licence is - © UNESCO 2021
This publication is available in Open Access under the Attribution-ShareAlike 3.0 IGO
(CC-BY-SA 3.0 IGO) license (http://creativecommons.org/licenses/by-sa/3.0/igo/).
By using the content of this publication, the users accept to be bound by the terms
of use of the UNESCO Open Access Repository (http://www.unesco.org/open-access/
terms-use-ccbysa-en).
